import { createTransport, type Transporter } from "nodemailer";
import axios from "axios";
import type { GeneratedSignal } from "./signals";

// Email configuration
let emailTransporter: Transporter | null = null;

function getEmailTransporter(): Transporter | null {
  if (emailTransporter) return emailTransporter;

  const smtpHost = process.env.SMTP_HOST || "smtp.gmail.com";
  const smtpPort = parseInt(process.env.SMTP_PORT || "587");
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (!smtpUser || !smtpPass) {
    console.warn("Email credentials not configured");
    return null;
  }

  emailTransporter = createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  return emailTransporter;
}

// Telegram configuration
const TELEGRAM_API_BASE = "https://api.telegram.org/bot";

function getTelegramToken(): string | null {
  return process.env.TELEGRAM_BOT_TOKEN || null;
}

// Send email notification
export async function sendEmailAlert(
  to: string,
  signal: GeneratedSignal
): Promise<{ success: boolean; error?: string }> {
  const transporter = getEmailTransporter();
  if (!transporter) {
    return { success: false, error: "Email not configured" };
  }

  try {
    const subject = `${signal.signal} SIGNAL - ${signal.symbol} (${signal.confidence}% Confidence)`;

    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #1a1a2e; color: #eee;">
        <div style="background: ${signal.signal === "BUY" ? "#16a34a" : signal.signal === "SELL" ? "#dc2626" : "#ca8a04"}; padding: 20px; text-align: center;">
          <h1 style="margin: 0; color: white;">🚀 AI Trading Alert</h1>
          <h2 style="margin: 10px 0 0 0; color: white;">${signal.signal} - ${signal.symbol}</h2>
        </div>
        
        <div style="padding: 20px;">
          <div style="background: #16213e; border-radius: 10px; padding: 20px; margin-bottom: 20px;">
            <h3 style="color: #60a5fa; margin-top: 0;">Signal Details</h3>
            <table style="width: 100%; color: #ddd;">
              <tr><td style="padding: 8px 0;"><strong>Symbol:</strong></td><td>${signal.symbol}</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Action:</strong></td><td style="color: ${signal.signal === "BUY" ? "#4ade80" : signal.signal === "SELL" ? "#f87171" : "#fbbf24"}; font-weight: bold;">${signal.signal}</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Confidence:</strong></td><td>${signal.confidence}%</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Entry Price:</strong></td><td>${signal.entryPrice.toLocaleString()}</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Take Profit:</strong></td><td style="color: #4ade80;">${signal.takeProfit.toLocaleString()}</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Stop Loss:</strong></td><td style="color: #f87171;">${signal.stopLoss.toLocaleString()}</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Risk/Reward:</strong></td><td>${signal.riskReward}</td></tr>
            </table>
          </div>

          <div style="background: #16213e; border-radius: 10px; padding: 20px; margin-bottom: 20px;">
            <h3 style="color: #60a5fa; margin-top: 0;">AI Analysis Scores</h3>
            <table style="width: 100%; color: #ddd;">
              <tr><td style="padding: 8px 0;"><strong>Technical Score:</strong></td><td>${signal.technicalScore}/100</td></tr>
              <tr><td style="padding: 8px 0;"><strong>AI Score:</strong></td><td>${signal.aiScore}/100</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Sentiment Score:</strong></td><td>${signal.sentimentScore}/100</td></tr>
              <tr><td style="padding: 8px 0;"><strong>Risk Score:</strong></td><td>${signal.riskScore}/100</td></tr>
            </table>
          </div>

          <div style="background: #16213e; border-radius: 10px; padding: 20px;">
            <h3 style="color: #60a5fa; margin-top: 0;">Analysis Reasons</h3>
            <ul style="color: #ddd; padding-left: 20px;">
              ${signal.reasons.map((r) => `<li style="padding: 4px 0;">${r}</li>`).join("")}
            </ul>
          </div>
        </div>

        <div style="background: #0f3460; padding: 15px; text-align: center; font-size: 12px; color: #888;">
          <p>Generated by AI Trading Platform at ${new Date().toUTCString()}</p>
          <p>This is not financial advice. Trade at your own risk.</p>
        </div>
      </div>
    `;

    await transporter.sendMail({
      from: `"AI Trading Bot" <${process.env.SMTP_USER}>`,
      to,
      subject,
      html: htmlBody,
    });

    return { success: true };
  } catch (error) {
    console.error("Email send error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

// Send Telegram notification
export async function sendTelegramAlert(
  chatId: string,
  signal: GeneratedSignal
): Promise<{ success: boolean; error?: string }> {
  const token = getTelegramToken();
  if (!token) {
    return { success: false, error: "Telegram bot token not configured" };
  }

  try {
    const emoji = signal.signal === "BUY" ? "🟢" : signal.signal === "SELL" ? "🔴" : "🟡";
    const message = `
${emoji} <b>AI TRADING SIGNAL</b> ${emoji}

<b>${signal.symbol}</b> → <b>${signal.signal}</b>

📊 <b>Confidence:</b> ${signal.confidence}%
💰 <b>Entry:</b> ${signal.entryPrice.toLocaleString()}
🎯 <b>Take Profit:</b> ${signal.takeProfit.toLocaleString()}
🛑 <b>Stop Loss:</b> ${signal.stopLoss.toLocaleString()}
📈 <b>Risk/Reward:</b> ${signal.riskReward}

🤖 <b>AI Scores:</b>
Technical: ${signal.technicalScore}/100
AI Model: ${signal.aiScore}/100
Sentiment: ${signal.sentimentScore}/100
Risk: ${signal.riskScore}/100

📝 <b>Reasons:</b>
${signal.reasons.map((r) => `• ${r}`).join("\n")}

⏰ ${new Date().toUTCString()}
    `;

    await axios.post(`${TELEGRAM_API_BASE}${token}/sendMessage`, {
      chat_id: chatId,
      text: message,
      parse_mode: "HTML",
    });

    return { success: true };
  } catch (error) {
    console.error("Telegram send error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

// Send test notifications
export async function testNotifications(
  email?: string,
  telegramChatId?: string
): Promise<{
  email?: { success: boolean; error?: string };
  telegram?: { success: boolean; error?: string };
}> {
  const testSignal: GeneratedSignal = {
    symbol: "BTCUSDT",
    market: "crypto",
    timeframe: "1h",
    timestamp: new Date(),
    signal: "BUY",
    confidence: 92.5,
    probability: { buy: 92.5, sell: 4.2, hold: 3.3 },
    technicalScore: 88,
    aiScore: 95,
    sentimentScore: 72,
    riskScore: 35,
    reasons: [
      "RSI oversold - potential reversal",
      "MACD bullish crossover",
      "Price above EMA20 and EMA50 - uptrend",
    ],
    entryPrice: 108450,
    stopLoss: 107500,
    takeProfit: 110200,
    riskReward: "2.5:1",
    passedRiskCheck: true,
  };

  const results: {
    email?: { success: boolean; error?: string };
    telegram?: { success: boolean; error?: string };
  } = {};

  if (email) {
    results.email = await sendEmailAlert(email, testSignal);
  }

  if (telegramChatId) {
    results.telegram = await sendTelegramAlert(telegramChatId, testSignal);
  }

  return results;
}

// Send welcome message to Telegram
export async function sendTelegramWelcome(
  chatId: string
): Promise<void> {
  const token = getTelegramToken();
  if (!token) return;

  const message = `
🎉 <b>Welcome to AI Trading Platform!</b>

You'll receive trading signals with:
✅ AI-powered analysis
✅ Entry/Stop Loss/Take Profit levels
✅ Confidence scores
✅ Risk assessment

Use /settings to configure your preferences.
Use /stop to pause notifications.

<i>Not financial advice. Trade responsibly.</i>
  `;

  try {
    await axios.post(`${TELEGRAM_API_BASE}${token}/sendMessage`, {
      chat_id: chatId,
      text: message,
      parse_mode: "HTML",
    });
  } catch (error) {
    console.error("Telegram welcome error:", error);
  }
}
